//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Entrevistadores
    {
        public A_Entrevistadores()
        {
            this.A_Giras = new HashSet<A_Giras>();
        }
    
        public int ID_Persona { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<A_Giras> A_Giras { get; set; }
    }
}
