//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class A_Giras
    {
        [Key]
        public int Gira { get; set; }
        public Nullable<int> Entrevistador { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaGira { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual A_Entrevistadores A_Entrevistadores { get; set; }
    }
}
